<ul>
  <li><a href="<?php echo __() ?>">Home</a></li>
  <li><a href="<?php echo __('about') ?>">About</a></li>
  <li><a href="<?php echo __('admin/create') ?>">Create</a></li>
</ul>

<hr>

<ul>
  <?php foreach($data as $id => $item) { ?>
  <li>
    <h3><a href="<?php echo __($item->link) ?>"><?php echo $item->title ?></a></h3>
    <p><?php echo $item->content ?></p>
    <small>Created: <?php echo date('d/m/Y', $item->created) ?></small> >> 
    <a href="<?php echo __('admin/update?id=' . $item->id) ?>">Edit</a>
  </li>
  <?php } ?>
</ul>

<hr>